version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "mudman1986"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
